import {
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowLeftIcon,
  ArrowsClockwiseIcon,
  ArrowsInIcon,
  ArrowsOutIcon,
  ArrowsOutCardinalIcon,
  CameraIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CheckIcon,
  CheckCircleIcon,
  CheckSquareOffsetIcon,
  CircleNotchIcon,
  ClipboardTextIcon,
  ClockIcon,
  CopyIcon,
  CrosshairIcon,
  CursorIcon,
  DatabaseIcon,
  DownloadSimpleIcon,
  EyeIcon,
  EyeSlashIcon,
  EyedropperIcon,
  FileIcon,
  FileCodeIcon,
  FileCssIcon,
  FileHtmlIcon,
  FileJpgIcon,
  FileJsIcon,
  FileJsxIcon,
  FileMdIcon,
  FilePlusIcon,
  FilePngIcon,
  FileSvgIcon,
  FileTsIcon,
  FileTsxIcon,
  FileTxtIcon,
  FileVideoIcon,
  FilmStripIcon,
  FolderSimpleIcon,
  FolderSimplePlusIcon,
  FrameCornersIcon,
  GearIcon,
  GridFourIcon,
  ImageIcon,
  IntersectIcon,
  KeyboardIcon,
  LightningIcon,
  LinkSimpleIcon,
  LinkSimpleBreakIcon,
  MagnetIcon,
  MagnetStraightIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  MinusIcon,
  MusicNoteIcon,
  MusicNotesIcon,
  PaletteIcon,
  PathIcon,
  PencilSimpleIcon,
  PlayCircleIcon,
  PlusIcon,
  QuestionIcon,
  RulerIcon,
  ScissorsIcon,
  SidebarSimpleIcon,
  SparkleIcon,
  SpeakerHighIcon,
  SpeakerLowIcon,
  SpeakerXIcon,
  SquareIcon,
  SquareSplitVerticalIcon,
  StackIcon,
  TextAaIcon,
  TextTIcon,
  TrashIcon,
  UploadSimpleIcon,
  WarningIcon,
  WarningCircleIcon,
  WaveformIcon,
  WavesIcon,
  XIcon,
} from "@phosphor-icons/react";
import type { Icon as PhosphorIcon, IconProps as PhosphorIconProps } from "@phosphor-icons/react";

/** The only sizes an icon may render at, in px. */
export const ICON_SIZES = [12, 14, 16, 20] as const;
type IconSize = (typeof ICON_SIZES)[number];

const ICONS = {
  arrowClockwise: ArrowClockwiseIcon,
  arrowCounterClockwise: ArrowCounterClockwiseIcon,
  arrowLeft: ArrowLeftIcon,
  arrowsClockwise: ArrowsClockwiseIcon,
  arrowsIn: ArrowsInIcon,
  arrowsOut: ArrowsOutIcon,
  arrowsOutCardinal: ArrowsOutCardinalIcon,
  camera: CameraIcon,
  caretDown: CaretDownIcon,
  caretLeft: CaretLeftIcon,
  caretRight: CaretRightIcon,
  check: CheckIcon,
  checkCircle: CheckCircleIcon,
  checkSquareOffset: CheckSquareOffsetIcon,
  circleNotch: CircleNotchIcon,
  clipboardText: ClipboardTextIcon,
  clock: ClockIcon,
  copy: CopyIcon,
  crosshair: CrosshairIcon,
  cursor: CursorIcon,
  database: DatabaseIcon,
  downloadSimple: DownloadSimpleIcon,
  eye: EyeIcon,
  eyeSlash: EyeSlashIcon,
  eyedropper: EyedropperIcon,
  file: FileIcon,
  fileCode: FileCodeIcon,
  fileCss: FileCssIcon,
  fileHtml: FileHtmlIcon,
  fileJpg: FileJpgIcon,
  fileJs: FileJsIcon,
  fileJsx: FileJsxIcon,
  fileMd: FileMdIcon,
  filePlus: FilePlusIcon,
  filePng: FilePngIcon,
  fileSvg: FileSvgIcon,
  fileTs: FileTsIcon,
  fileTsx: FileTsxIcon,
  fileTxt: FileTxtIcon,
  fileVideo: FileVideoIcon,
  filmStrip: FilmStripIcon,
  folderSimple: FolderSimpleIcon,
  folderSimplePlus: FolderSimplePlusIcon,
  frameCorners: FrameCornersIcon,
  gear: GearIcon,
  gridFour: GridFourIcon,
  image: ImageIcon,
  intersect: IntersectIcon,
  keyboard: KeyboardIcon,
  lightning: LightningIcon,
  linkSimple: LinkSimpleIcon,
  linkSimpleBreak: LinkSimpleBreakIcon,
  magnet: MagnetIcon,
  magnetStraight: MagnetStraightIcon,
  magnifyingGlass: MagnifyingGlassIcon,
  magnifyingGlassMinus: MagnifyingGlassMinusIcon,
  magnifyingGlassPlus: MagnifyingGlassPlusIcon,
  minus: MinusIcon,
  musicNote: MusicNoteIcon,
  musicNotes: MusicNotesIcon,
  palette: PaletteIcon,
  path: PathIcon,
  pencilSimple: PencilSimpleIcon,
  playCircle: PlayCircleIcon,
  plus: PlusIcon,
  question: QuestionIcon,
  ruler: RulerIcon,
  scissors: ScissorsIcon,
  sidebarSimple: SidebarSimpleIcon,
  sparkle: SparkleIcon,
  speakerHigh: SpeakerHighIcon,
  speakerLow: SpeakerLowIcon,
  speakerX: SpeakerXIcon,
  square: SquareIcon,
  squareSplitVertical: SquareSplitVerticalIcon,
  stack: StackIcon,
  textAa: TextAaIcon,
  textT: TextTIcon,
  trash: TrashIcon,
  uploadSimple: UploadSimpleIcon,
  warning: WarningIcon,
  warningCircle: WarningCircleIcon,
  waveform: WaveformIcon,
  waves: WavesIcon,
  x: XIcon,
} as const satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICONS;

type IconProps = Pick<PhosphorIconProps, "className" | "style"> & {
  name: IconName;
  size: IconSize;
  /** Accessible name; without it the glyph is decorative and hidden from assistive tech. */
  title?: string;
  /** The one place a heavier weight is allowed: a toggled-on or active control. */
  selected?: boolean;
};

export function Icon({ name, size, title, selected = false, ...rest }: IconProps) {
  const Glyph = ICONS[name];
  return (
    <Glyph
      size={size}
      weight={selected ? "fill" : "regular"}
      alt={title}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      {...rest}
    />
  );
}
